import Array2
maxSize = 10 
arr = Array2.Array(maxSize) 
arr.insert(77) 
arr.insert(99)
arr.insert("foo")
arr.insert("bar")
arr.insert(44)
arr.insert(55)
arr.insert(12.34)
arr.insert(0)
arr.insert("baz")
arr.insert(-17)
print("Array containing", len(arr), "items")
arr.traverse()
print("Search for 12 returns", arr.search(12))
print("Search for 12.34 returns", arr.search(12.34))
print("Deleting 0 returns", arr.delete(0))
print("Deleting 17 returns", arr.delete(17))
print("Setting item at index 3 to 33")
arr.set(3, 33)
print("Array after deletions has", len(arr), "items")
arr.traverse()
max_num = arr.getMaxNum()
print("Maximum Number in the array:", max_num)
print("Array containing", len(arr), "items")
arr.traverse()
max_num = arr.deleteMaxNum()
if max_num is not None:
    print("Maximum Numero en la matriz:", max_num)

print("Matriz después de eliminar el número máximo tiene", len(arr), "items")
arr.traverse()